# -*- coding: utf-8 -*-
"""Yahtzee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pvgTeKBiKEJZeHMgd3gp-Hv4P00Qybj

Yahtzee is a fun dice game where you roll five dice to score points by creating specific combinations. Here's a breakdown of the rules:

**Objective:**  Score the most points by rolling the dice and filling up a scorecard with various scoring combinations.

**Players:**  Yahtzee can be played with multiple players (usually 2-6) taking turns, or as a single-player game.

**Gameplay:**

* Each round, a player starts by rolling all five dice.
* You can then re-roll any or all of the dice up to two more times in the same round, trying to create a scoring combination.
* After each roll (including the first one), you decide whether to score that roll in one of the categories on the scorecard, or re-roll again.

**Scoring:**

* The scorecard has 13 boxes for different scoring categories, like Upper Section (ones, twos, threes, etc.) where you sum the value of each matching die, or Lower Section (three of a kind, four of a kind, full house, etc.) where you score based on specific dice combinations.  
* You can only fill each category once on the scorecard.
* If none of the rolls give you a scoring opportunity in a category, you must mark a zero in that box.

**Yahtzee!**

* The highest scoring combination is a Yahtzee, which is rolling all five dice with the same number. The first Yahtzee you score is worth 50 points, and any subsequent Yahtzees are worth 100 points each (as long as you've already scored a Yahtzee).

**End of the Game:**

* The game ends after all players have filled up their scorecards (marked all 13 boxes).
* Players add up their scores from each category, including any Yahtzee bonuses, and the player with the highest total score wins!

**Tips:**

* Strategize which categories to fill based on the dice you roll.
* Don't be afraid to re-roll for a Yahtzee, but be mindful of using up all your rolls.
* Pay attention to what categories other players might be going for, so you can block them if possible (by filling the category yourself).

There are Yahtzee scorecards available online or you can find them included in Yahtzee game sets.  Have fun rolling!
"""

class Die:
    def __init__(self) -> None:
        self.sides = 6
        self.faces = list(range(1, self.sides + 1))
        self.frozen = False
        self.roll()

    def roll(self):
        if not self.frozen:
            self.value = random.choice(self.faces)

    def freeze(self):
        self.frozen = True

    def unfreeze(self):
        self.frozen = False

    def __repr__(self):
        return str(self.value)

def demo():
    scorecard = {category: None for category in YAHTZEE_CATEGORIES}
    dice = [Die() for _ in range(5)]  # Initialize dice for the first round

    for round in range(1, 14):  # Play 13 rounds
        print("\nRound", round)

        # Roll dice
        for die in dice:
            die.roll()

        print(dice)
        print({category: category.score(dice) for category in YAHTZEE_CATEGORIES})

        # Input and freeze dice
        input_text = input("Enter dice to freeze (1-5), comma-separated: ")
        to_freeze = []
        for item in input_text.split(","):
            try:
                value = int(item.strip())
                if 1 <= value <= 5:
                    to_freeze.append(value)
                else:
                    print(f"Ignoring invalid value: {value}. Please enter a number between 1 and 5.")
            except ValueError:
                print(f"Ignoring invalid input: {item}. Please enter integers separated by commas.")

        # Freeze selected dice
        for number in to_freeze:
            dice[number - 1].freeze()

        print(dice)
        print({category: category.score(dice) for category in YAHTZEE_CATEGORIES})

        # Update scorecard
        for category in YAHTZEE_CATEGORIES:
            if scorecard[category] is None:
                scorecard[category] = category.score(dice)

        print("\nScorecard after Round", round)
        print(scorecard)

        # Unfreeze all dice for the next round
        for die in dice:
            die.unfreeze()

demo()

